# Site settings
title: Android Developer
email: emedinaa@gmail.com
description: Android , Java , Kotlin , Swift , Js , Python, ActionScript ,C++, Clean code, Design patterns 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emedinaa.github.io/" # the base hostname & protocol for your site
twitter_username: eduardomedina
github_username:  emedinaa

# Build settings
markdown: kramdown
