# Site settings
title: Android-IOS Developer
email: emedinaa@gmail.com
description: Líder Técnico Android en Online Studio Instructor de aplicaciones móviles en ISIL Miembro de la comunidad GDGLima Administrador del Grupo Android.pe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emedinaa.github.io/" # the base hostname & protocol for your site
twitter_username: eduardomedina
github_username:  emedinaa

# Build settings
markdown: kramdown
